CATEGORIES = [
    # Category: skincare
    ('Skincare', 'Moisturisers', ' Oily & Combination Skin', None, 'https://us.feelunique.com/skin/moisturisers/oily-combination-skin'),
    ('Skincare', 'Moisturisers', ' Day Creams', None, 'https://us.feelunique.com/skin/moisturisers/day-creams'),
    ('Skincare', 'Moisturisers', ' Night Creams',  'Oily & Combination Skin', 'https://us.feelunique.com/skin/moisturisers/night-creams/oily-combination-skin'),
    ('Skincare', 'Moisturisers', ' Night Creams', None, 'https://us.feelunique.com/skin/moisturisers/night-creams'),
    ('Skincare', 'Moisturisers', ' Balms & Gels', None, 'https://us.feelunique.com/skin/moisturisers/balms-gels'),
    ('Skincare', 'Moisturisers', 'Creams & Lotions', None, 'https://us.feelunique.com/skin/moisturisers/creams-lotions'),
    ('Skincare', 'Moisturisers', 'oils', None, 'https://us.feelunique.com/skin/moisturisers/oils'),
    ('Skincare', 'Cleansers', 'Oily and combination skin', None, 'https://us.feelunique.com/skin/cleansers/combination-oily-skin'),
    ('Skincare', 'Cleansers', 'Mature skin', None, 'https://us.feelunique.com/skin/cleansers/mature-skin'),
    ('Skincare', 'Cleansers', 'Cleansing Tools', None, 'https://us.feelunique.com/skin/cleansers/cleansing-tools'),
    ('Skincare', 'Cleansers', 'wipes', None, 'https://us.feelunique.com/skin/cleansers/wipes-pads'),
    ('Skincare', 'Cleansers','Face Cloths & Sponges', None, 'https://us.feelunique.com/skin/cleansers/face-cloths'),
    ('Skincare', 'Cleansers', 'Facial Cleansing Brushes',None, 'https://us.feelunique.com/skin/cleansers/facial-cleansing-brushes'),
    ('Skincare', 'Cleansers', 'Micellar Water', None, 'https://us.feelunique.com/skin/cleansers/micellar-water'),
    ('Skincare', 'Cleansers', 'Face mists & sprays', None, 'https://us.feelunique.com/skin/cleansers/mists-sprays'),
    ('Skincare', 'sun & tan', ' Sun Cream', None, 'https://us.feelunique.com/skin/sun-tan/sun-cream'),
    ('Skincare', 'sun & tan', 'After sun', None, 'https://us.feelunique.com/skin/sun-tan/after-sun'),
    ('Skincare', 'sun & tan', 'Tan optimisers', None, 'https://us.feelunique.com/skin/sun-tan/tan-accelerators'),
    ('Skincare', 'sun & tan', 'Fake tan', None, 'https://us.feelunique.com/skin/sun-tan/fake-tan'),
    ('Skincare', 'Eye care', 'Eye creams', None, 'https://us.feelunique.com/skin/eye-care/eye-creams'),
    ('Skincare', 'Eye care', 'Eye gels', None, 'https://us.feelunique.com/skin/eye-care/eye-gels'),
    ('Skincare', 'Eye care', 'Eye patches', None, 'https://us.feelunique.com/skin/eye-care/eye-patches'),
    ('Skincare', 'Toners', None, None, 'https://us.feelunique.com/skin/toners'),
    ('Skincare', 'Skin Concerns', 'Anti-ageing', None, 'https://us.feelunique.com/skin/skin-concerns/anti-ageing'),
    ('Skincare', 'Skin Concerns', 'Anti-Dark Spots', None, 'https://us.feelunique.com/skin/skin-concerns/anti-dark-spots'),
    ('Skincare', 'Skin Concerns', 'Anti-Pollution', None, 'https://us.feelunique.com/skin/skin-concerns/anti-pollution'),
    ('Skincare', 'Skin Concerns', 'Blemish-prone Skin', None, 'https://us.feelunique.com/skin/skin-concerns/blemish-prone-problem-skin'),
    ('Skincare', 'Skin Concerns', 'Eczema & Dermatitis', None, 'https://us.feelunique.com/skin/skin-concerns/eczema-dermatitis'),
    ('Skincare', 'Skin Concerns', 'Neck & Decollete Care', None,'https://us.feelunique.com/skin/skin-concerns/neck-care'),
    ('Skincare', 'Skin Concerns', 'Pigmentation', None,'https://us.feelunique.com/skin/skin-concerns/pigmentation'),
    ('Skincare', 'Skin Concerns', 'Redness', None,'https://us.feelunique.com/skin/skin-concerns/redness')
    # TODO -> autres catégories
]
